# Generated by Django 4.1 on 2022-08-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('recipe', models.TextField(max_length=1500)),
                ('is_published', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='food/%Y/%m/%d/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.category')),
            ],
            options={
                'ordering': ('-is_published',),
            },
        ),
    ]
